[package]
name = "test-realloc-alignment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
fixed = []

[dependencies]
cty = "0.2.2"
